
#### Recuperar información del pokemon ditto 
GET http://localhost:3100/pokemon/ditto

####
GET http://localhost:3100/pokemon?limit=100000&offset=0


#### Para crear un nuevo pokemon
POST  http://localhost:3100/pokemon
Content-Type: application/json
{
    "name":"Picachu",
    "type":"Electric",
    
}
